openai:
  api_key: KLmy1EtC4jRcrlXSK2xPgesG5Hgc533A
  base_url: http://Bedroc-Proxy-THtYZpmCMIzd-1859376833.us-east-1.elb.amazonaws.com/api/v1
  model: anthropic.claude-3-5-sonnet-20240620-v1:0
  modelSonnet: anthropic.claude-3-5-sonnet-20240620-v1:0
  modelHaiku: anthropic.claude-3-haiku-20240307-v1:0

input_folder:
  path: D:\00_WIP\07_AI_PowerAutomate\Batch-Processing-Text-Files-with-OpenAI\Input

output_messagefolder:
  path: D:\00_WIP\07_AI_PowerAutomate\Batch-Processing-Text-Files-with-OpenAI\OutputMessage

output_csvfolder:
  path: D:\00_WIP\07_AI_PowerAutomate\Batch-Processing-Text-Files-with-OpenAI\OutputCSV

prompt:
  text: |
    The following email contains information about IT project recruitment. Please extract the information into a CSV format according to the items below. The output should be in Japanese.

    ## Rules
    1. If multiple projects are mentioned in the email, output each project on a separate row.
    2. Each column in the CSV should correspond to the specified items. Do not include any other information.
    3. The response should only contain the CSV data, without any additional information.
    4. Format the CSV as follows:
      - Use commas (,) to separate each column.
      - The first row should contain column names, with data starting from the second row.
      - **IMPORTANT**: Enclose fields in double quotes (") if they contain any of the following:
        - Commas
        - Line breaks
        - Double quotes (escape these by doubling them, e.g., "" for a single ")
      - Do not use quotes for fields that don't require them.
    5. Use the same language as the case introduction if there are no special language requirements.
    6. Include the information about monthly expected work hours / FTE in the project summary.

    ## Items to extract (column names should be in Japanese)
    提供元案件番号,委託元,業界,PJフェーズ,モジュール,SAP案件,単価,募集人数,開始日,終了日,勤務地,案件概要,必須要件,歓迎要件,言語力,メインポジション,商流

    ## Descriptions for each item
    [Your existing descriptions here]

    案件概要: Provide a comprehensive project description (minimum 500 words) using bullet points. Include:
    1. All information from other sections.
    2. Project details (e.g., age restrictions, number of interviews, business flow).
    3. Monthly expected work hours / FTE.
    4. Any relevant remarks or additional information.
    5. Ensure all pertinent information is captured in a clear, organized manner.
    6. **IMPORTANT**: This field must always be enclosed in double quotes (") due to its length and potential for commas and line breaks.

    [Rest of your existing descriptions]

    ## Email content to extract from
    {email_content}

    ## Output format example (in Japanese)
    提供元案件番号,委託元,業界,PJフェーズ,モジュール,SAP案件,単価,募集人数,開始日,終了日,勤務地,案件概要,必須要件,歓迎要件,言語力,メインポジション,商流
    AB-123,アクセンチュア,製造業,要件定義,SD,〇,100万円,1,即日,2024/12/31,東京,"• SAP導入プロジェクト。
    • 月間想定工数160時間、FTE 1.0。
    • [その他の詳細な案件概要]",SAP SDモジュール経験,製造業経験,日本語,コンサルタント,"弊社2次請け（エンド→元請け→弊社）"

    ## Final Reminder
    Always enclose the 案件概要 field in double quotes, and use double quotes for any other fields containing commas, line breaks, or double quotes. Double-check your output to ensure proper quoting is applied where necessary.

max_tokens: 4096

kintone:
  domain: arkconsulting.cybozu.com
  app_id: 63
  api_token: n4Zgbz1nv0HGh3tJdn0zZ7wqJ84rc1oUgLDEpRPB